import { StyleSheet } from "react-native";
import { COLORS, FONT, SIZES } from "../app/shared/constants";

export default StyleSheet.create({
  rootContainer: {
    flex: 1,
    display: "flex",
    position: "relative",
    marginVertical: 5,
    width: "100%",
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  mainContainer: {
    flex: 1,
    margin: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
  },
  container: {
    flexDirection: "column",
    marginTop: 15,
    flex: 1,
    width: "100%",
    position: "relative",
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  tabsContainer: {
    width: "100%",
    marginTop: SIZES.medium,
  },
  tab: (activeCategory, item) => ({
    paddingVertical: SIZES.small / 2,
    paddingHorizontal: SIZES.small,
    borderRadius: SIZES.medium,
    borderWidth: 1,
    borderColor: activeCategory === item ? COLORS.secondary : COLORS.gray2,
  }),
  tabText: (activeCategory, item) => ({
    fontFamily: FONT.medium,
    color: activeCategory === item ? COLORS.secondary : COLORS.gray2,
  }),
  topNewsTitle: {
    flexShrink: 1,
    position: "relative",
    fontSize: 18,
    marginBottom: 3,
    fontWeight: 700,
  },
  topNewsTitleBar: {
    flexShrink: 1,
    width: 50,
    height: 3,
    backgroundColor: COLORS.red,
    bottom: -2,
    marginBottom: 10,
    borderRadius: 5,
    zIndex: 999,
    position: "relative",
  },
  topNewsContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 6,
    padding: 20,
    height: "100%",
    width: "100%",
    marginVertical: 10,
  },
  renderContainer: {
    flex: 1,
    height: "100%",
    width: "100%",
    marginHorizontal: 5,
    marginVertical: 10,
    borderRadius: 18,
    backgroundColor: COLORS.white,
  },
  renderListContainer: {
    flex: 1,
    flexShrink: 1,
    flexGrow: 1,
    padding: 5,
    position: "relative",
  },
  listContainer: {
    flex: 1,
    flexGrow: 1,
    paddingTop: 6,
    paddingRight: 0,
    marginRight: 2,
  },
  itemListTitle: {
    flex: 1,
    minWidth: 335,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
    fontSize: SIZES.small,
    color: COLORS.webBlue,
    fontFamily: FONT.roboto.regular,
  },
  itemContainer: {
    flex: 1,
    flexGrow: 1,
    width: "100%",
    height: "100%",
    alignSelf: "center",
    marginHorizontal: 20,
  },
  itemTitle: {
    flexShrink: 1 / 50,
    width: 340,
    alignSelf: "center",
    textAlign: "center",
    fontSize: SIZES.small,
    color: COLORS.webBlue,
    marginTop: 5,
    marginRight: 5,
    marginBottom: -10,
    marginLeft: 5,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    fontFamily: FONT.roboto.bold,
  },
  footerContainer: {
    alignContent: "center",
  },
  categoryTitleBarContainer: {
    flexDirection: "row",
    flex: 1,
    flexShrink: 1,
    flexGrow: 1,
    width: "100%",
    marginTop: 30,
  },
  newsCategoryTitle: {
    flex: -1,
    flexGrow: 1,
    flexShrink: 1,
    color: COLORS.webBlue,
    fontSize: SIZES.large,
    marginTop: 12,
    marginRight: 0,
    marginBottom: 12,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    textTransform: "none",
    fontFamily: FONT.roboto.bold,
  },
  categoryTitleLine: {
    flex: -1,
    flexShrink: -20,
    flexGrow: 1,
    marginHorizontal: 3,
    marginTop: 32.5,
    borderTopColor: COLORS.webBlue,
    borderTopWidth: 1,
    width: "100%",
  },

  containerSlider: (selectedCategory, item) => ({
    width: 250,
    padding: SIZES.xLarge,
    backgroundColor:
      selectedCategory === item.id ? COLORS.darkBlue : COLORS.webBlue,
    borderRadius: SIZES.medium,
    ...SHADOWS.medium,
    shadowColor: COLORS.white,
  }),
  logoContainer: (selectedCategory, item) => ({
    width: 200,
    height: 150,
    backgroundColor:
      selectedCategory === item.id ? COLORS.darkBlue : COLORS.webBlue,
    borderRadius: SIZES.medium,
  }),
  logoImage: {
    borderRadius: SIZES.xSmall,
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  newsTitleSlider: (selectedCategory, item) => ({
    fontSize: SIZES.medium,
    fontFamily: FONT.roboto.regular,
    color: selectedCategory === item.id ? COLORS.white : COLORS.white,
    marginTop: SIZES.small / 1.5,
  }),
  newsPubTitleSlider: (selectedCategory, item) => ({
    fontSize: SIZES.xSmall,
    fontFamily: FONT.roboto.regular,
    color: selectedCategory === item.id ? COLORS.creamWhite : COLORS.gray2,
    marginTop: SIZES.small / 1.5,
    bottom: 5,
    left: 25,
    position: "absolute",
  }),
  infoContainer: {
    marginTop: SIZES.large,
  },
  categoryNameSlider: (selectedCategory, item) => ({
    fontSize: SIZES.small,
    fontFamily: FONT.roboto.light,
    color: selectedCategory === item.id ? COLORS.creamWhite : COLORS.gray2,
    position: "absolute",
    textTransform: "uppercase",
    bottom: 0,
  }),
  infoWrapper: {
    flexDirection: "row",
    marginTop: 5,
    justifyContent: "flex-start",
    alignItems: "center",
  },
});
